






--데이터 조회 SELECT  컬럼명1, 컬럼명 2. ....from 테이블명

SELECT STUNO, STU_NAME, EMAIL, ADDRESS, ENTER_DATE, ETC
FROM HR.STUDENTS;
--선택되는 컬럼은 필요한 것들로 합니다. 명령어 한개 실행은 CTRL+ENTER
SELECT STUNO, STU_NAME FROM STUDENTS;
--모든 카럼을 선택할떄는 WILDCART 문자 *로 대체
SELECT *FROM STUDENTS ;

--데이터 조회에 사용되는 조건 추가는 WHERE 뒤에 조건식 작성
SELECT * FROM STUDENTS WHERE STUNO =1;
SELECT * FROM STUDENTS WHERE STU_NAME  ='이다현';
SELECT * FROM STUDENTS WHERE ENTER_DATE  <'2020-06-01';
SELECT STUNO ,STU_NAME, ENTER_DATE , ETC FROM STUDENTS s WHERE ETC IS NULL ;
SELECT STUNO ,STU_NAME, ENTER_DATE , ETC FROM STUDENTS s WHERE ETC IS NOT NULL ;

SELECT COUNT(*)from STUDENTS s ;
SELECT MAX(STUNO)from STUDENTS s ;
SELECT MIN(STUNO)from STUDENTS s ;



--데이터 추가 (삽입) : INSERT INto 테이블명(컬럼명1, 컬럼명2, ...) value(값1, 값2,...)

INSERT INTO HR.STUDENTS
(STUNO, STU_NAME, EMAIL, ADDRESS, ENTER_DATE, ETC)
VALUES(0, '', '', '', '', '');

--데이터 수정 : UPDATE 테이블 명 SET 컬럼명1 = 값1, 컬럼명2=값2,....;

UPDATE HR.STUDENTS
SET STUNO=0, STU_NAME='', EMAIL='', ADDRESS='', ENTER_DATE='', ETC='';

--데이터 행단위 삭제 : DELETE FROM 테이블 명 WHERE 컬럼명 1 = 값1 AND 컬럼명 2 = 값2
--											삭제할 행에 대한 조건

DELETE FROM HR.STUDENTS
WHERE STUNO=0 AND STU_NAME='' AND EMAIL='' AND ADDRESS='' AND ENTER_DATE='' AND ETC='';
